name: Survival
version: ${project.version}
main: dev.foolen.survival.Survival
api-version: 1.13

commands:
  setspawn:
    usage: /<command>
    description: Sets spawn location to senders current location.
  spawn:
    usage: /<command>
    description: Teleports sender to spawn location.
  setwarp:
    usage: /<command> <name>
    description: Sets warp location to senders current location.
  delwarp:
    usage: /<command> <name>
    description: Deletes a warp location.
  warps:
    usage: /<command>
    description: Shows a list of all available warps.
  warp:
    usage: /<command>
    description: Teleports sender to warp location.

permissions:
  survival.*:
    description: Grants access to all survival plugin features.
    children:
      survival.command.*: true
  survival.command.*:
    description: Grants access to all commands.
    children:
      survival.command.setspawn: true
      survival.command.spawn: true
      survival.command.setwarp: true
      survival.command.delwarp: true
      survival.command.warps: true
      survival.command.warp: true
  survival.command.setspawn:
    description: Grants access to the /setspawn command.
    default: op
  survival.command.spawn:
    description: Grants access to the /spawn command.
    default: op
  survival.command.setwarp:
    description: Grants access to the /setwarp command.
    default: op
  survival.command.delwarp:
    description: Grants access to the /delwarp command.
    default: op
  survival.command.warps:
    description: Grants access to the /warps command.
    default: op
  survival.command.warp:
    description: Grants access to the /warp command.
    default: op
