name: Survival
version: ${project.version}
main: dev.foolen.survival.SurvivalPlugin
api-version: 1.13

commands:
  setspawn:
    usage: /<command>
    description: Sets spawn location to sender's current location.
  spawn:
    usage: /<command>
    description: Teleports sender to spawn location.
  setwarp:
    usage: /<command> <name>
    description: Sets warp location to sender's current location.
  delwarp:
    usage: /<command> <name>
    description: Deletes a warp location.
  warps:
    usage: /<command>
    description: Shows a list of all available warps.
  warp:
    usage: /<command>
    description: Teleports sender to warp location.
  sethome:
    usage: /<command> <name>
    description: Sets home location to sender's current location.
  delhome:
    usage: /<command> <name>
    description: Deletes a home location.
  homes:
    usage: /<command>
    description: Shows a list of sender's homes.
  home:
    usage: /<command> <name>
    description: Teleports sender to home location.
  rules:
    usage: /<command>
    description: Shows a list of rules.
  fly:
    usage: /<command>
    description: Toggles sender's fly mode.
  gamemode:
    usage: /<command> <mode>
    description: Changes sender's gamemode.
  gm:
    usage: /<command> <mode>
    description: Changes sender's gamemode.
  teleport:
    usage: /<command> <name>
    description: Teleports sender to a player.
  tp:
    usage: /<command> <name>
    description: Teleports sender to a player.
  tpa:
    usage: /<command> <name>
    description: Requests teleport approve to a player.
  tpaccept:
    usage: /<command> <name>
    description: Accepts teleport request from a player.
  tpdeny:
    usage: /<command> <name>
    description: Denies teleport request from a player.
  tppos:
    usage: /<command> <name>
    description: Teleports sender to a location.

permissions:
  survival.*:
    description: Grants access to all survival plugin features.
    children:
      survival.command.*: true
  survival.command.*:
    description: Grants access to all commands.
    children:
      survival.command.setspawn: true
      survival.command.spawn: true
      survival.command.setwarp: true
      survival.command.delwarp: true
      survival.command.warps: true
      survival.command.warp: true
      survival.command.sethome: true
      survival.command.delhome: true
      survival.command.homes: true
      survival.command.home: true
      survival.command.rules: true
      survival.command.fly: true
      survival.command.gamemode: true
      survival.command.teleport: true
      survival.command.tpa: true
      survival.command.tpaccept: true
      survival.command.tpdeny: true
      survival.command.tppos: true
  survival.command.setspawn:
    description: Grants access to the /setspawn command.
    default: op
  survival.command.spawn:
    description: Grants access to the /spawn command.
    default: op
  survival.command.setwarp:
    description: Grants access to the /setwarp command.
    default: op
  survival.command.delwarp:
    description: Grants access to the /delwarp command.
    default: op
  survival.command.warps:
    description: Grants access to the /warps command.
    default: op
  survival.command.warp:
    description: Grants access to the /warp command.
    default: op
  survival.command.sethome:
    description: Grants access to the /sethome command.
    default: op
  survival.command.delhome:
    description: Grants access to the /delhome command.
    default: op
  survival.command.homes:
    description: Grants access to the /homes command.
    default: op
  survival.command.home:
    description: Grants access to the /home command.
    default: op
  survival.command.rules:
    description: Grants access to the /rules command.
    default: op
  survival.command.fly:
    description: Grants access to the /fly command.
    default: op
  survival.command.gamemode:
    description: Grants access to the /gamemode command.
    default: op
  survival.command.teleport:
    description: Grants access to the /teleport command.
    default: op
  survival.command.tpa:
    description: Grants access to the /tpa command.
    default: op
  survival.command.tpaccept:
    description: Grants access to the /tpaccept command.
    default: op
  survival.command.tpdeny:
    description: Grants access to the /tpdeny command.
    default: op
  survival.command.tppos:
    description: Grants access to the /tppos command.
    default: op
